# Generated by Django 3.2.8 on 2021-10-28 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventJoined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_joining_date', models.DateField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events_App.event')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
